apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstuff-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstuff-controller
  template:
    metadata:
      labels:
        app: hotstuff-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: controller
        image: uliaskar/hotstuff-controller:latest # update path later
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "sleep infinity"]
        ports:
            - containerPort: 8080
        securityContext:
            runAsUser: 0 
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault  
      - name: node-exporter   # the sidecar
        image: prom/node-exporter:latest
        ports:
            - containerPort: 9100
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: hotstuff-data-pvc

      
